<div class="level<?= $this->level ?>">
  <?php $this->renderBlock('news/comment-item', array(
    'c' => $c,
    'in_comment_page' => 0,
  )) ?> 
  <a href="/comment/reply?id=<?= $c->id ?>" class="btn-small">回应</a>
  <ul class="comment-list level<?= $this->level+1 ?>">
    <?php foreach ($this->c->getCommentList() as $key => $value): ?>
      <li>
        <?php $this->renderBlock('news/comment-item-wrap', array(
          'c' => $value,
          'level' => $this->level+1,
          'in_comment_page' => 0,
        )) ?> 
      </li>
    <?php endforeach ?>
  </ul>
</div>
