<button class="upvote-btn" data-id="<?= $n->id ?>">赞</button>
<h2>
  <a href="<?= $n->getUrl() ?>"><?= htmlspecialchars($n->title) ?></a>
</h2>

<?php if ($n->url): ?>
<span class="site">(<?= $n->getSite() ?>)</span>
<?php endif ?>

<div class="detail-wrap">
  <span><?= $n->readableTime() ?></span>
  <span><?= htmlspecialchars($n->user()->name) ?> 发</span>
  <span id="Point<?= $n->id ?>"><?= $n->point ?>分</span>
  <a href="/talk/<?= $n->id ?>">
    <?= $n->countComment() ? $n->countComment().'个' : '' ?>讨论
  </a>
</div>
