<button class="upvote-btn" data-id="<?= $n->id ?>">赞</button>
<h2>
  <a href="<?= $n->getUrl() ?>"><?= $n->title ?></a>
</h2>

<?php if ($n->url): ?>
<span class="site">(<?= $n->getSite() ?>)</span>
<?php endif ?>

<div class="detail-wrap">
  <span><?= $n->readableTime() ?></span>
  <span><?= $n->username ?> 发</span>
  <span id="Point<?= $n->id ?>"><?= $n->point ?>分</span>
  <a href="">讨论</a>
</div>
