<a href="<?= $this->currentUserId ? 'javascript:void(0);' : '/login?'.http_build_query(array('back' => '/', 'msg' => '你需要登录才能投票')) ?>">
  <img class="upvote-btn" data-id="<?= $n->id ?>" title="赞" src="/img/arrow_up.png">
</a>
<h2>
  <a href="<?= $n->getUrl() ?>"><?= htmlspecialchars($n->title) ?></a>
</h2>

<?php if ($n->url): ?>
<span class="site">(<?= $n->getSite() ?>)</span>
<?php endif ?>

<div class="detail-wrap">
  <span><?= $n->readableTime() ?></span>
  <span><?= htmlspecialchars($n->user()->name) ?> 发</span>
  <span><span id="Point<?= $n->id ?>"><?= $n->point ?></span>分</span>
  |
  <a href="/talk/<?= $n->id ?>">
    <?= $n->countComment() ? $n->countComment().'个' : '' ?>讨论
  </a>
</div>
