<?php
/**
 * @file    index
 * @author  ryan <cumt.xiaochi@gmail.com>
 * @created Jul 17, 2012 9:51:11 AM
 */
?>
<div class="index content-wrap">
  <?php $this->renderBlock('layout/header') ?>

  <ul class="news-list">
    <?php foreach ($this->news as $key => $value): ?>
      <li class="news-item">
        <?php $this->renderBlock('news/item', array('n' => $value)) ?>
      </li>
    <?php endforeach ?>
  </ul>
</div>
