<?php
/**
 * @file    index
 * @author  ryan <cumt.xiaochi@gmail.com>
 * @created Jul 17, 2012 9:51:11 AM
 */
?>
<div class="index content-wrap">
  <div class="login-btn-wrap">
    <?php if ($this->currentUserId): ?>
      <span><?= $this->currentUser->name ?></span>
      |
      <a href="/login/out">登出</a>
    <?php else: ?>
      <a href="/login">登录</a>
    <?php endif ?>
  </div>

  <div class="logo-wrap"><img src="/img/logo.png"></div>
  <div class="nav">
    <a href="/welcome">欢迎</a>
    |
    <a href="/comment/">評論</a>
    |
    <a href="/submit">开新话题</a>
  </div>

  <ul class="news-list">
    <?php foreach ($this->news as $key => $value): ?>
      <li class="news-item">
        <?php $this->renderBlock('news/item', array('n' => $value)) ?>
      </li>
    <?php endforeach ?>
  </ul>
</div>
