<h2>登录</h2>
<form action="/login/auth" method="post">
  <div>
    <input type="text" name="username" placeholder="用户名">
  </div>
  <div>
    <input type="password" name="password" placeholder="密码">
  </div>
  <button type="submit">登录</button>
</form>

<h2>注册</h2>
<form action="/login/add" method="post">
  <div>
    <input type="text" name="username" placeholder="用户名">
  </div>
  <div>
    <input type="password" name="password" placeholder="密码">
  </div>
  <button type="submit">注册</button>
</form>
